### ISSUE TITLE
File scrolls to top on save

### ISSUE THREAD

**Issue by MarcPinnell** [biati-digital/nova-php-cs-fixer#14]
After editing a file and then saving, file scrolls back to the first line. Obviously a bit annoying when you are on line 300!

Verified by turning off 'PHP CS Fixer'. Behavior goes away (but of course so does the auto formatting!).

Running Nova 6.2 build 271290
Other active Extensions: "advanced PHP" and "baigoAligner"

**Comment by biati-digital** [comment]
I'm not able to replicate that error. I'm also in the latest version. Did  you try disabling other extensions?

**Comment by MarcPinnell** [comment]
I am using version 3.02.
Yes, I have confirmed the behavior with no other extensions activated.

**Comment by biati-digital** [comment]
I'm not able to replicate the error, I doubt this has something to do with the extension, the code has not changed since version 2 and there has been several updates since then.

Since Nova 6 I'm having a lot of problems, multiple cursors on save, the extension Emmet stopped working completely and I had to disable other extensions because they were acting weird since Nova 6. The fact is that Panic introduce new bugs with each release.

I'm afraid there's not much I can do as the extension simply tells Nova to replace the code with the formatted code.

**Comment by biati-digital** [comment]
Yes, please do, give it a try with a future Nova update, I'm closing this for now.

**Comment by biati-digital** [comment]
Just for the record. This is the response I received from Panic about this issue introduced in Nova 6.2

> Thanks for the report! We made some changes to this API in Nova 6.2 to address certain other bugs, but unfortunately introduced this issue. We're aware of the problem and working to fix this in our next update in a way that'll preserve the bugfixes we made in 6.2 while also not sending you to the top of the document. Sorry for the trouble!

**Comment by MarcPinnell** [comment]
Thanks for the followup!

**Comment by biati-digital** [comment]
Panic fixed this in the latest version 7.1
