### ISSUE TITLE
Fatal error using WordPress coding standard

### ISSUE THREAD

**Issue by Graphnic** [biati-digital/nova-php-cs-fixer#22]
Using version 4.1.0 when setting the Coding Standard to 'WordPress' a fatal error is generated:

```
Fatal error: Declaration of WeDevs\Fixer\SpaceInsideParenthesisFixer::applyFix(SplFileInfo $file, PhpCsFixer\Tokenizer\Tokens $tokens) must be compatible with PhpCsFixer\AbstractFixer::applyFix(SplFileInfo $file, PhpCsFixer\Tokenizer\Tokens $tokens): void in /Users/xxxxx/Library/Application Support/Nova/Extensions/biati.phpcsfixer/rules/SpaceInsideParenthesisFixer.php on line 63

FATAL ERROR
[
 "\n",
 "Fatal error: Declaration of WeDevs\\Fixer\\SpaceInsideParenthesisFixer::applyFix(SplFileInfo $file, PhpCsFixer\\Tokenizer\\Tokens $tokens) must be compatible with PhpCsFixer\\AbstractFixer::applyFix(SplFileInfo $file, PhpCsFixer\\Tokenizer\\Tokens $tokens): void in /Users/xxxxx/Library/Application Support/Nova/Extensions/biati.phpcsfixer/rules/SpaceInsideParenthesisFixer.php on line 63\n"
]
```

I am running PHP 7.4.  I tried the default installed by Homebrew (8.1.4) which generated a warning that the version was too high.

All the other coding standards appear to run correctly, so it does appear to be related to the WordPress standard in particular.

Thanks for your work on this extension!

**Comment by Graphnic** [comment]
Thanks, I couldn't get to the bottom of it unfortunately.

**Comment by biati-digital** [comment]
Sorry to hear that, it worked correctly when we implemented the WordPress rules, we use it on a few projects but phpcsfixer is constantly updated so the rules must also be updated.

Nova sucks for PHP so I went back to php storm. Hopefully someone can invest some time and make a PR.

**Comment by Graphnic** [comment]
> Nova sucks for PHP

Yes, I'm beginning to realise that.  I was once a Coda user but moved to PHP Storm, which is overkill for my needs... but getting a code formatter to work with WP coding standards in Nova is no easy task.

**Comment by biati-digital** [comment]
I used the editor an entire year and created 3 extensions (Advanced new file, Text Tools and PHP CS Fixer) i really wanted to like the editor but i lost a lot of work because it crashed every week, there was a bug where the editor changed the names of folders without notice, there's 2 bugs that i reported 8 months ago that they were able to replicate but are still there. I admire Panic and i prefer native apps but Nova has been out only for 1 year and it requires more time to be a decent editor.

If you work with WordPress save yourself the trouble and keep using PHP Storm, PHPCS Fixer (the underlaying tool this extension uses) is designed only for PHP code, when you mix PHP and HTML, PHPCS Fixer will make a mess, we tried to solve that including a HTML formatter but still requires work. We only used WordPress a couple of times but because it does not use a template engine like twig or blade sometimes the code was not formatted correctly. Jetbrains has the time, the people and money to make it work correctly on PHP Storm.

**Comment by emilorol** [comment]
@Graphnic the wordpress error you are seeing has to do with the path not been escaped.

I submitted a fix in this PR #25

**Comment by biati-digital** [comment]
The latest version "4.1.2" includes the fixes by @emilorol, just tested the WordPress Coding Standard and seems to work correctly.

**Comment by emilorol** [comment]
@biati-digital the version is `4.2.1` (small typo there) also do you plan to update this repo with the latest code changes?

Thank you for your time and effort.

**Comment by biati-digital** [comment]
Hi @emilorol you are right, the latest version is `4.2.1` also the repo has been updated with the latest version.

Thank you for fixing the WordPress rules and for sponsoring the update. 

I'll close this issue as it appears to be fixed.
