### ISSUE TITLE
Halts with total Nova failure on HTML prettifying

### ISSUE THREAD

**Issue by konstantin83** [biati-digital/nova-php-cs-fixer#5]
Don't know how, but simple HTML file causes formatter to fail. 
First:
http://joxi.ru/V2V9Mx6tkVvQPm?d=1
and then:
http://joxi.ru/zAN91KMtjxKqB2?d=1

**Comment by biati-digital** [comment]
Hi, Please share the code so i can make some tests

**Comment by konstantin83** [comment]
[home-new.html.zip](https://github.com/biati-digital/nova-php-cs-fixer/files/5690666/home-new.html.zip)

**Comment by biati-digital** [comment]
ohhh that's only HTML, the file extension it's also .html, this is a PHP formatter so it requires a PHP file (or that's the idea as it should only be available for PHP files) although this extension is 100% capable of formatting only HTML it was not created for that purpose, i recommend you to install the Prettier extension by Alexander Weiss to format simple HTML files.

**Comment by konstantin83** [comment]
I see. Strange. Because in PHPStorm for example CMD+ALT+L formats everything whatever it is and whatever file format there is. Nova should learn it too. It would be great if you could make it.

**Comment by biati-digital** [comment]
If you compare Nova with PHPStorm you're going to have a bad time, Nova has been out just a couple of months, PHPStorm is way ahead of Nova and it will take months/years to offer even some basic functionalities (believe me, i've opened several future requests for the most basic things months ago). I hope this improves over time but i do not develop Nova, i'm just a developer that created a formatting tool for PHP.

I really hope Nova improves over time as there are many things extension developers can not do because of the limited API.

**Comment by konstantin83** [comment]
Yes, I understand that you are a developer of an extremely useful extension. Thank you for that. I was thinking of Nova as a very native and handy and cartoon-line Mac OS app. Actually it has everything I need, except for local History of files editing and instant upload files to Remote ftp on save action. As it does heavy and overloaded with unneeded functions PHPStorm

**Comment by biati-digital** [comment]
If it works for you that's awesome, i think that for PHP and other languages it's really limited, i really enjoy apps well designed and native it's a huge plus and I hope Nova improves because i like it. 

For remote upload on save you could try "control+command+s" it will trigger save and publish and for formatting files that are not PHP i "recommend" the Prettier extension, Prettier it's a little slow and with some minified files does not even work, the alternative is the extension Beautify, i did not try it but it uses JS-Beautify under the hood (same as this extension) and it's really fast. I checked the code and i find it really really basic so there's no much to customize or even some basics like format on save.

Anyway, this is still really new, i'll continue to work and improve this extension as i use it daily for work.

**Comment by konstantin83** [comment]
God bless you )
